version: '3'

services:
  postgres:
    image: postgres:16-alpine
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password!
      POSTGRES_DB: sandbox

networks:
  default:
    driver: bridge
    